name: test

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    tags-ignore:
      - "*"

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
        working-directory:  packages/react-native-ultimate-config
      - run: npm test
        working-directory:  packages/react-native-ultimate-config
