name: test

on:
  push:
    tags-ignore:
      - "*"

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: cd packages/react-native-ultimate-config; npm install
      - run: npm test
