name: test

on: push

jobs:
  test-ios-config:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        working-directory: example
        run: yarn
      - name: init env
        working-directory: example
        run: yarn setenv .env
      - name: pods (ios only)
        working-directory: example/ios
        run: pod install
      - name: print file
        working-directory: example
        run: cat node_modules/react-native-ultimate-config/ios/ConfigValues.h
      - name: install detox stuff
        run: |
          brew tap wix/brew
          brew install applesimutils
          npm install -g detox
      - name: build
        working-directory: example
        run: detox build --configuration ios.sim.release
      - name: Test if config has been injected
        working-directory: example/ios
        run: |
          /usr/libexec/PlistBuddy -c "Print :CFBundleDisplayName" build/Build/Products/Release-iphonesimulator/example.app/Info.plist 2>/dev/null | grep 'RNUC Demo'
      - name: e2e test
        working-directory: example
        run: detox test --configuration ios.sim.release


  test-android-config:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          yarn
          cd android
          yarn setenv .env
          # ./gradlew assembleDebug
          detox build --configuration android.emu.release
        working-directory: example  
      - name: Test if config has been injected
        run: |
          grep 'public static final String APP_NAME = "RNUC Demo"' android/app/build/generated/source/buildConfig/release/com/example/BuildConfig.java
          xmllint --xpath '//resources/string[@name="APP_NAME"]'  android/app/build/generated/res/resValues/release/values/gradleResValues.xml | grep "RNUC Demo"
          grep APP_NAME android/app/build/generated/not_namespaced_r_class_sources/release/r/com/example/R.java
        working-directory: example  
      - name: e2e test
        working-directory: example
        run: detox test --configuration android.emu.release

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: yarn
      - run: yarn test
